# Generated by Django 5.2 on 2025-04-29 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weekly_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=1000)),
                ('is_immutable', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('signature', models.TextField(blank=True)),
                ('weekly_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to='weekly_logs.weeklylog')),
            ],
            options={
                'verbose_name': 'Logbook Entry',
                'verbose_name_plural': 'Logbook Entries',
            },
        ),
    ]
