# Generated by Django 5.2 on 2025-06-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbookentry',
            name='version',
        ),
    ]
