# Generated by Django 5.2 on 2025-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_entries', '0002_remove_logbookentry_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookentry',
            name='original_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
