# Generated by Django 5.2 on 2025-06-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_entries', '0003_logbookentry_original_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbookentry',
            options={},
        ),
    ]
