# Generated by Django 5.2 on 2025-04-29 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='rejected', max_length=10)),
                ('week_no', models.PositiveIntegerField()),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='logbooks.logbook')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('week_no', 'logbook'), name='unique_week_no_per_logbook')],
            },
        ),
    ]
