# Generated by Django 5.2 on 2025-06-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_logs', '0002_weeklylog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='week_no',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
