# Generated by Django 5.2 on 2025-06-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_logs', '0004_alter_weeklylog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_approval', 'Pending Approval')], default='pending_approval', max_length=20),
        ),
    ]
