# Generated by Django 5.2 on 2025-04-29 10:03

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15, validators=[apps.users.models.validate_contact])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('division', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
