# Generated by Django 5.2 on 2025-04-29 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logbook_entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookEntryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='log_photos/')),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='logbook_entries.logbookentry')),
            ],
            options={
                'verbose_name': 'Logbook Entry Photo',
                'verbose_name_plural': 'Logbook Entry Photos',
            },
        ),
    ]
