# Generated by Django 5.2 on 2025-04-29 11:26

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('matricule_num', models.CharField(max_length=10, validators=[apps.utils.validations.validate_matricule_num])),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
