# Generated by Django 5.2 on 2025-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='private_key',
            field=models.TextField(blank=True),
        ),
    ]
