# Generated by Django 5.2 on 2025-06-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='encrypted_private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='salt',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
