# Generated by Django 5.2 on 2025-06-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_encrypted_private_key_student_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='salt',
        ),
    ]
