# Generated by Django 5.2 on 2025-06-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_salt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='private_key',
            new_name='public_key',
        ),
    ]
