# Generated by Django 5.2 on 2025-06-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_rename_private_key_student_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600')], default=400, max_length=5),
            preserve_default=False,
        ),
    ]
