# Generated by Django 5.2 on 2025-04-29 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer'),
        ),
    ]
