# Generated by Django 5.2 on 2025-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='students',
            field=models.ManyToManyField(to='students.student'),
        ),
    ]
