# Generated by Django 5.2 on 2025-05-04 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0001_initial'),
        ('companies', '0001_initial'),
        ('internships', '0004_initial'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='students',
        ),
        migrations.AddField(
            model_name='internship',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='students.student'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InternshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('job_description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_years.academicyear')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_requests', to='companies.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_requests', to='students.student')),
            ],
            options={
                'verbose_name': 'Internship Request',
                'verbose_name_plural': 'Internship Requests',
            },
        ),
    ]
