# Generated by Django 5.2 on 2025-05-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_remove_internship_students_internship_student_and_more'),
        ('lecturers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecturers.lecturer'),
        ),
    ]
