# Generated by Django 5.2 on 2025-05-04 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_alter_internship_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
