# Generated by Django 5.2 on 2025-05-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0007_internship_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ongoing', 'Ongoing'), ('completed', 'completed'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20),
        ),
    ]
