# Generated by Django 5.2 on 2025-06-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_alter_internship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='internship_reports/'),
        ),
        migrations.AddField(
            model_name='internship',
            name='report_generated',
            field=models.BooleanField(default=False),
        ),
    ]
