# Generated by Django 5.2 on 2025-06-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_alter_internship_status'),
        ('logbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='logbook',
            constraint=models.UniqueConstraint(fields=('internship',), name='unique_logbook_per_internship'),
        ),
    ]
