# Generated by Django 5.2 on 2025-05-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('student', 'Student'), ('lecturer', 'Lecturer'), ('supervisor', 'Supervisor'), ('company_admin', 'Company Admin'), ('super_admin', 'Super Admin')], default='user', max_length=15),
        ),
    ]
