# Generated by Django 5.2 on 2025-04-29 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('total_score', models.IntegerField(default=0, editable=False)),
                ('comments', models.TextField(blank=True, max_length=1000)),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='internships.internship')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
