# Generated by Django 5.2 on 2025-04-29 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='internship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='internships.internship'),
        ),
    ]
