# Generated by Django 5.2 on 2025-06-27 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('lecturers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='school',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='departments.department'),
        ),
    ]
