# Generated by Django 5.2 on 2025-04-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_year', models.IntegerField(help_text='Start year of the academic period')),
                ('end_year', models.IntegerField(help_text='End year of the academic period')),
                ('label', models.CharField(blank=True, editable=False, help_text="Automatically generated as 'start_year/end_year'", max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
